@hostname = http://localhost:3333

###########################################
POST {{hostname}}/repositories
content-type: application/json

{
	"title": "Umbriel",
	"techs": ["React", "ReactNative", "TypeScript", "ContextApi"],
	"url": "https://github.com/Rocketseat/umbriel",
	"likes": 1
}

###########################################

GET {{hostname}}/repositories

###########################################
// POST LIKES
POST {{hostname}}/repositories/6f171c23-aa7e-4ca7-9c8c-405a986d8708/like
content-type: application/json

###########################################

DELETE {{hostname}}/repositories

###########################################

put {{hostname}}/repositories/377a8466-d9bd-4f57-b0f9-532f430f6037
content-type: application/json

{
	"title": "Umbriel 2",
	"techs": ["React 2", "ReactNative 2", "TypeScript 2", "ContextApi 2"],
	"likes": 5

}

###########################################